version: '3.9'

services:
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"
    depends_on:
      - backend